### PR TITLE
Python 3 json compatibility

### PR DESCRIPTION
**Pull request by epenet**

### CODE REVIEW

**Comment by jamesremuscat** [comment]
Hi @epenet,

Thanks for the PR.

I'm curious as to why this is necessary. Do you have a requirement to use `json` rather than `simplejson`?

Python 2.x compatibility is not a concern as the rest of the code is Python 3-specific.

**Comment by epenet** [comment]
Hi @jamesremuscat,
According to [this page](https://simplejson.readthedocs.io/en/latest/), you can see that json is included as standard from 2.6+, whereas simplejson was an external library and should only be used for 2.5 compatibility.
If you are targetting Python3 anyway, then I think it's better to just drop all references to simplejson.

**Comment by jamesremuscat** [comment]
Fair enough; I don't see much advantage in doing so, but I suppose it's one less dependency.

On which note: please could you also remove the reference in `setup.py`?

**Comment by epenet** [comment]
I've updated the PR

**Comment by jamesremuscat** [comment]
Thanks, merged to `develop`.

**Pull request merged**
